server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dbuser
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    mode: LEGACYHTML5